name: Deploy to Google Cloud

on:
  push:
    branches:
      - master  # Trigger the workflow on push to the master branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Step 2: Set up Google Cloud SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # Step 3: Build and Push Docker Image using Cloud Build
      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --config cloudbuild.yaml

      # Step 4: Deploy the Docker Image to Google Cloud Run
      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy text-summarizer \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/text-summarizer:latest \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated